export enum ESTIMATE {
  ADVANCED_SEARCH = 'Advanced Search',
  ADD_NEW_FORMULA = 'Add New Formula',
  ADD_NEW_GROUP = 'Add New Group',
  ACTIVITY_LOGS = 'Activity Logs',
  ESTIMATE_TITLE = 'ESTIMATE',
  ESTIMATE_TEMPLATE = 'Estimate template',
  FORMULA_CENTER = 'Formula Center',
  FORMULA_CREATION_CENTER = 'Formula Creation Center',
  ASSEMBLE = 'Assemble',
  ASSEMBLE_NAME = 'Assemble Name',
  DESCRIPTION = 'Description',
  DATA_ENTRY = 'Data Entry',
  UNIT = 'Unit',
  QUANTITY = 'Quantity',
  COLOR_CODE = 'Color Code',
  SHOW_COLOR = 'Show Color',
  MATH_ACTION = 'Math Action',
  ADD_FORMULA = 'Add Formula',
  DATA_LIBRARY = ' Data Library',
  SELECT_MATERIAL = 'Select Material',
  MARKUP = 'Markup =',
  COST = 'Cost =',
  CHARGE = 'Charge =',
  QUANTITY_EQUAL = 'Quantity =',
  DESCRIPTION_OF_FORMULA = 'Description of Formula',
  FORMULA_SCENARIO = 'Formula Scenario',
  TITLE_PO_FORMULA = 'PO FORMULA',
  ADD_NEW_UNIT = 'Add New Unit',
  UPDATE_UNIT = 'Update Unit',
  ENSURE_VALUE_IS_POSITIVE = 'Ensure value >= 0',
  DELETE_UNIT = 'Delete Unit',
  UPDATE_DESCRIPTION = 'Update Description',
  ADD_NEW_DESCRIPTION = 'Add New Description',
  UPDATE_DESCRIPTION_LIBRARY = 'Update Description',
  ADD_NEW_DESCRIPTION_LIBRARY = 'Add New Description',
  DELETE_DESCRIPTION_LIBRARY = 'Delete Description',
  DELETE_DESCRIPTION_LIBRARY_SUCCESS = 'Deleted description successfully',
  DELETE_DESCRIPTION_LIBRARY_FAIL = 'Failed to delete description',
  ADD_NEW_DESCRIPTION_LIBRARY_SUCCESS = 'Created description successfully',
  ADD_NEW_DESCRIPTION_LIBRARY_FAIL = 'Failed to create description',
  UPDATE_DESCRIPTION_LIBRARY_SUCCESS = 'Updated description successfully',
  UPDATE_DESCRIPTION_LIBRARY_FAIL = 'Failed to Update description',
  SAVE_FORMULA = 'Save Formula',
  DELETE_ASSEMBLE = 'Delete Assemble',
  THIS_LIST_FORMULA_BELOW_FROM_THE_LIBRARY = 'The list formula below from the library',
  LIST_FORMULA = 'List Formula',
  DETAIL = 'Detail',
  CATEGORY = 'Category',
  CONTACT_DESCRIPTION = 'Contact Description',
  DATA_VIEW = 'Data View',
  FORMULAS_LIBRARY_NOTE = 'The description below from the description library',
  SEARCH = 'Search',
  FILTER = 'Filter',
  ADD_NEW_GROUP_BUTTON = 'Add New Group',
  GROUP_NAME = 'Group Name',
  ADD_NEW = 'Create New Group',
  CLEAR_ALL = 'Clear All',
  LIST_FORMULAS = 'List Formulas',
  SELECT_FROM_LIBRARY_IS_REQUIRED = 'Please choose a library to continue',
  NEW_GROUP_FORMULAS_CREATE_SUCCESS = 'Created New Formula Group Successfully',
  NEW_GROUP_FORMULAS_CREATE_FAIL = 'Failed to Create New Group',
  PLEASE_CHOOSE_AT_LEAST_ONE_FORMULA = 'Please choose at least one formula to create new group',
  CLEAR_ALL_SUCCESS = 'Clear all selected formula successfully',
  CLEAR_ALL_FAIL = 'Failed to clear all selected formula',
  PLACE_HOLDER_DES_SCE = 'Your comment or notes',
  CONFIRM_CREATE_GROUP = 'Are you sure you want to create new group?',
  ADD_NEW_ASSEMBLE_SUCCESS = 'Created assemble successfully',
  ADD_NEW_ASSEMBLE_FAIL = 'Failed to create assemble',
  UPDATE_ASSEMBLE_SUCCESS = 'Updated assemble successfully',
  UPDATE_ASSEMBLE_FAIL = 'Failed to update assemble',
  SURE_UPDATE_ASSEMBLE = 'Are you sure to do update Assemble?',
  DESCRIPTION_OF_ASSEMBLE = 'Description of Assemble',
  PLEASE_ENTER_ASSEMBLE_NAME = 'Please enter assemble name',
  CATALOG_LINK = 'Catalog Link',
  COMPANY_LINK = 'Company Link',
  CREATE = 'Create',
  SAVE = 'Save',
  CANCEL = 'Cancel',
  UPDATE = 'Update',
  DELETE_FORMULA = 'Delete Formula',
  DELETE_FORMULA_SUCCESS = 'Deleted formulas successfully',
  DELETE_FORMULA_FAIL = 'Failed to delete formulas',
  DELETE_GROUP_FORMULA_SUCCESS = 'Deleted group formulas successfully',
  DELETE_GROUP_FORMULA_FAIL = 'Failed to delete group formulas'
}

export enum ESTIMATE_VALIDATE {
  INPUT_ERROR = 'Invalid Input',
  QUANTITY_ERROR = 'Invalid Quantity',
  NAME_FORMULA = 'Name of Formula is required!',
  NAME_DATA_ENTRY = 'Name of data entry is required',
  FORMULA = 'Formula is required!',
  TEMPLATE_NAME = 'Template Name',
  DETAIL = 'Detail',
  CATEGORY = 'Category'
}
export enum DATA_ENTRY {
  ADD_DATA_ENTRY = 'Add Data Entry',
  UPDATE_DATA_ENTRY = 'Update Data Entry',
  DELETE_DATA_ENTRY = 'Delete Data Entry',
  ADD_TYPE_IN = 'Add With Type In',
  ADD_DROPDOWN = 'Add With Dropdown',
  DROPDOWN = 'Dropdown',
  TYPE_IN = 'Type In',
  ADD_NEW_DATA_ENTRY_LIBRARY_SUCCESS = 'Created data entry successfully',
  ADD_NEW_DATA_ENTRY_LIBRARY_FAIL = 'Failed to create data entry',
  UPDATE_DATA_ENTRY_LIBRARY_SUCCESS = 'Updated data entry successfully',
  UPDATE_DATA_ENTRY_LIBRARY_FAIL = 'Failed to update data entry',
  SURE_UPDATE_DATA_ENTRY = 'Are you sure to do update data entry?',
  NAME_DROPDOWN = 'Name Dropdown',
  VALUE_DROPDOWN = 'Value Dropdown',
  WARNING_CAN_NOT_REMOVE_FIRST_DATA_ENTRY = 'Can not remove first data entry'
}

export enum AddModeDataEntry {
  TYPE_IN,
  DROPDOWN
}
