export enum LEAD {
  GENERAL = 'General',
  CONTACT_INFO = 'Contact Info',
  ACTIVITIES = 'Activities',
  PROPOSALS = 'Proposals',
  PHOTOS = 'Photos',
  OTHERS = 'Others',
  EXISTING_CONTACTS = 'Existing Contacts',
  ADD_CONTACT = 'Add Contact',
  LINK_CONTACT_TO_LEAD = 'Add to Lead',
  UPDATE_CONTACT = 'Update Contact',
  SAVE_CONTACT = 'Save',
  COMUNICATIONS = 'Comunications',
  LEAD_DETAILS = 'Lead Details',
  NEW_ACTIVITY = 'New Activity',
  UPDATE_ACTIVITY = 'Update Activity',
  ADVANCED_SEARCH = 'Advanced Search',
  ESTIMATE_REVENUE = 'Estimated Revenue',
  PROJECTED_SALES_DATE = 'Projected Sales Date',
  DELETE_ACTIVITY_SUCCESS = 'Delete multiple activities successfully',
  DELETE_ACTIVITY_FAILED = 'Failed to delete multiple activities',
  ADD_NEW_LEAD_TAG_SUCCESS = 'Created new lead tags successfully',
  ADD_NEW_LEAD_TAG_FAILED = 'Failed to create new lead tags',
  ADD_LEAD_CONTACT_ACTION_SUCCESS = 'Create new contact actions successfully',
  ADD_LEAD_CONTACT_ACTION_FAILED = 'Failed to create new contact actions',
  UPDATE_LEAD_CONTACT_SUCCESS = 'Updated lead contact successfully',
  UPDATE_LEAD_CONTACT_FAILED = 'Failed to update your lead contact.',
  ADD_LEAD_PROJECT_TYPE_ACTION_SUCCESS = 'Created new project type action successfully',
  ADD_LEAD_PROJECT_TYPE_ACTION_FAILED = 'Failed to create new project type actions',
  ADD_LEAD_TAG_ACTION_SUCCESS = 'Created new tag action successfully',
  ADD_LEAD_TAG_ACTION_FAILED = 'Failed to create new tag actions',
  ADD_NEW_SOURCE_ACTION_SUCCESS = 'Created new source action successfully',
  ADD_NEW_SOURCE_ACTION_FAILED = 'Failed to create new source action',
  LINK_MULTIPLE_CONTACT_SUCCESS = 'Linked multiple contacts successfully',
  LINK_MULTIPLE_CONTACT_FAILED = 'Failed to link multiple contacts',
  DELETE_MULTIPLE_CONTACT_SUCCESS = 'Deleted multiple contacts successfully',
  DELETE_MULTIPLE_CONTACT_FAILED = 'Failed to delete multiple contacts',
  DELETE_MULTIPLE_LEAD_ACTION_SUCCES = 'Deleted contact successfully',
  DELETE_MULTIPLE_LEAD_ACTION_FAILED = 'Failed to delete contact',
  SAVED_FILTER_LABEL = 'Saved Filter',
  REMOVE_CONTACT_CONFIRM = 'Are you sure you want to delete this contact?',
  DELETE_PHOTO_CONFIRM = 'Are you sure you want to delete this photo?'
}

export enum FILTER_GRID {
  SHOW = 'Show Columns',
  HIDE = 'Hide Columns',
  TEMPLATE = 'Template',
  GRID_SETTINGS = 'Grid Settings',
  MANAGE_GRID_SETTING = 'Manage Grid Settings',
  MANAGE_GRID_SETTING_DESCRIBE = 'Manage your grid views and select your default view for the Lead Opportunities page',
  CREATE = 'create',
  UPDATE = 'update',
  YOUR_SAVE_VIEW = 'Your Save View',
  SUCCESS = 'Successfully!',
  FAILED = 'Failed',
  NAME_FILTER = 'Name Filter Grid'
}
