export enum SCHEDULE {
  EVENT = 'Event',
  TODO = 'Todo',
  TODO_INFORMATION = 'Todo-Information',
  DAILY_LOG = 'Daily Log',
  OUTDOOR_HOME = 'OUTDOOR HOME',
  TAGLINE = 'TAGLINE',
  CHECKLIST_ITEM = 'Checklist Items',
  ATTACHMENTS = 'Attachments',
  DRAG_ADD_NEW_FILE = 'Drag/ Add New File',
  DEFAULT_DAILY_LOG_SETTINGS = 'Default Daily Log Settings',
  PRIORITY = 'Priority',
  SETUP = 'Setup',
  DEFAULT_DAILY_LOG_SHARE_SETTINGS = 'Default Daily Log Share Settings',
  MESSAGING = 'Messaging',
  VIEWER_AND_NOTIFICATION = 'Viewer & Notification Settings',
  SEND = 'Send',
  SHOW = 'Show',
  CUSTOM_FIELD = 'Custom Field',
  DAILY_LOGS_CUSTOM_FIELDS = 'Daily Logs Custom Fields',
  TODO_SETUP = 'To-Do’s Setup',
  SELECT_OPTION = 'Select Option',
  TODO_CUSTOM_FIELDS = 'To-Do’s Custom Fields',
  DAILYLOG_TEMPLATES = 'Daily Log Templates',
  COMMENT = 'Comment',
  DEFAULT_VIEWING_OPTION = 'Default Viewing Option',
  DEFAULT_BUILDER_VIEW = 'Default builder view',
  DEFAULT_OWNER_SCHEDULE_DISPLAY = 'Default Owner Schedule Display',
  DEFAULT_NOTIFICATION_OPTIONS = 'Default Notification Options',
  DEFAULT_SCHEDULE_ITEM_REMINDERS = 'Default Schedule item reminders',
  SEND_CONFIRMATION_REQUEST_WITH_SCHEDULE_ITEM_REMINDERS = 'Send confirmation request with schedule item reminders',
  DEFAULT_NOTIFY_LINKED_SUBS_VENDORS = 'Default notify linked subs/vendors',
  OTHER_SETTING = 'Other Settings',
  SHOW_TIMES_FOR_HOURLY_ITEMS = 'Show times for hourly items on Calendar - Month view',
  SHOW_JOB_NAME = 'Show job name on Calendar - Month/Week/Day views for All Listed Jobs',
  AUTOMATICALLY_MARK_ITEMS_COMPLETE = 'Automatically mark items complete',
  NEW_SCHEDULE_ITEMS_DEFAULT_SHOW = 'New Schedule items - Default show subs/vendors',
  INCLUDE_HEADER_ON_SCHEDULE_PDF_EXPORT = 'Include header on schedule PDF export',
  ADD_PHASES = 'Add Phases',
  PROJECT = 'Project',
  SCHEDULE_ITEM = 'Schedule item',
  PHASES = 'Phases',
  SETTING = 'Setting',
  TEMPLATE_NAME = 'Templates Name',
  OTHER_TEMPLATE = 'Other Template',
  START_TO_START = 'Start to start',
  FINISH_TO_START = 'Finish to start',
  CHOOSE_TO_DO_LINK_TO_EVENT = 'Choose to do link to event',
  UPDATE_TODO_INFO_SUCCESS = 'Update Todo info successfully',
  UPDATE_TODO_INFO_FAIL = 'Failed to update Todo info',
  UPDATE_EVENT_ACTION_SUCCESS = 'Updated Event action successfully',
  UPDATE_EVENT_ACTION_FAIL = 'Failed to update Event action ',
  DAILY_LOG_CREATE_NEW_CMT_SUCCESS = 'Created new comment successfully',
  DAILY_LOG_CREATE_NEW_CMT_FAIL = 'Failed to create new comment',
  DAILY_LOG_UPDATE_CMT_SUCCESS = 'Updated comment successfully',
  DAILY_LOG_UPDATE_CMT_FAIL = 'Failed to update comment',
  DAILY_LOG_DELETE_CMT_SUCCESS = 'Deleted comment successfully',
  DAILY_LOG_DELETE_CMT_FAIL = 'Failed to delete comment',
  DAILY_LOG_UPDATE_SETTING_SUCCESS = 'Updated daily log setting successfully',
  DAILY_LOG_UPDATE_SETTING_FAIL = 'Failed to update daily log setting',
  DAILY_LOG_DELETE_MULTIPLE_TEMPLATE_SUCCESS = 'Deleted multiple template successfully',
  DAILY_LOG_DELETE_MULTIPLE_TEMPLATE_FAIL = 'Failed to delete multiple template',
  DAILY_LOG_CREATE_NEW_TEMPLATES_SUCCESS = 'Created new templates successfully',
  DAILY_LOG_CREATE_NEW_TEMPLATES_FAIL = 'Failed to create new templates',
  DAILY_LOG_UPDATE_TEMPLATE_SUCCESS = 'Updated template successfully',
  DAILY_LOG_UPDATE_TEMPLATE_FAIL = 'Failed to update template',
  EVENT_CREATE_NEW_PHASE_SUCCESS = 'Created new phase successfully',
  EVENT_CREATE_NEW_PHASE_FAIL = 'Failed to create new phase',
  EVENT_UPDATE_SETTING_SUCCESS = 'Updated event setting successfully',
  EVENT_UPDATE_SETTING_FAIL = 'Failed to update event setting',
  DELETE_EVENT_SUCCESS = 'Deleted event successfully',
  DELETE_EVENT_FAIL = 'Failed to delete event',
  DELETE_DAILY_LOG_SUCCESS = 'Deleted daily log successfully',
  DELETE_DAILY_LOG_FAIL = 'Failed to delete daily log',
  DELETE_TODO_SUCCESS = 'Deleted todo successfully',
  DELETE_TODO_FAIL = 'Failed to Delete todo'
}
export enum SCHEDULE_EVENT_TYPE {
  START_TO_START = 'start_to_start',
  FINISH_TO_START = 'finish_to_start'
}
export enum TIME_BAR {
  DAY = 'Day',
  WEEK = 'Week',
  MONTH = 'Month',
  YEAR = 'Year',
  SCHEDULE = 'Schedule'
}
export enum ACTION_LABEL {
  ACTION = 'Action',
  FILTER = 'Filter',
  TEMPLATE = 'Template',
  EXPORT = 'Export',
  SETTING = 'Setting'
}
export enum REQUIRED_SCHEDULE {
  CHARACTER = 'Ensure this field has no more than 128 characters',
  EVENT_TITLE = 'Event title is required',
  DUE_DATE = 'Due date can not be before start date',
  WORK_DAY = 'The number must be greater than 0!',
  LEAD = 'Lead is required',
  PHASE_LABEL = 'Label is required',
  REASON_TITLE = 'Title is required',
  SHIFT_REASON = 'Shift reason is required'
}
